package com.yufop.tran.mapper;

import com.yufop.tran.pojo.table.TransUnit;
import com.yufop.tran.pojo.table.TransUnitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TransUnitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transunit
     *
     * @mbggenerated Sun Jun 18 19:39:34 CST 2023
     */
    int countByExample(TransUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transunit
     *
     * @mbggenerated Sun Jun 18 19:39:34 CST 2023
     */
    int deleteByExample(TransUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transunit
     *
     * @mbggenerated Sun Jun 18 19:39:34 CST 2023
     */
    int deleteByPrimaryKey(Integer transunitid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transunit
     *
     * @mbggenerated Sun Jun 18 19:39:34 CST 2023
     */
    int insert(TransUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transunit
     *
     * @mbggenerated Sun Jun 18 19:39:34 CST 2023
     */
    int insertSelective(TransUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transunit
     *
     * @mbggenerated Sun Jun 18 19:39:34 CST 2023
     */
    List<TransUnit> selectByExample(TransUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transunit
     *
     * @mbggenerated Sun Jun 18 19:39:34 CST 2023
     */
    TransUnit selectByPrimaryKey(Integer transunitid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transunit
     *
     * @mbggenerated Sun Jun 18 19:39:34 CST 2023
     */
    int updateByExampleSelective(@Param("record") TransUnit record, @Param("example") TransUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transunit
     *
     * @mbggenerated Sun Jun 18 19:39:34 CST 2023
     */
    int updateByExample(@Param("record") TransUnit record, @Param("example") TransUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transunit
     *
     * @mbggenerated Sun Jun 18 19:39:34 CST 2023
     */
    int updateByPrimaryKeySelective(TransUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transunit
     *
     * @mbggenerated Sun Jun 18 19:39:34 CST 2023
     */
    int updateByPrimaryKey(TransUnit record);
}